-- Create Products Table
create table if not exists products (
  id bigint generated by default as identity primary key,
  title text not null,
  price numeric not null,
  description text,
  image text,
  category text,
  is_new boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table products enable row level security;

-- Policies for Products
-- Check if policy exists before creating to avoid recreating/overwriting
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'products' and policyname = 'Public products are viewable by everyone') then
    create policy "Public products are viewable by everyone"
      on products for select
      using ( true );
  end if;

  if not exists (select 1 from pg_policies where tablename = 'products' and policyname = 'Anyone can insert products') then
    create policy "Anyone can insert products"
      on products for insert
      with check ( true );
  end if;
end $$;


-- Storage Bucket for Images
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

-- Policies for Storage
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Public Access') then
    create policy "Public Access"
      on storage.objects for select
      using ( bucket_id = 'product-images' );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Public Upload') then
    create policy "Public Upload"
      on storage.objects for insert
      with check ( bucket_id = 'product-images' );
  end if;
end $$;


-- ==============================================================================
-- NEW SECTION: Profiles Table for User Management & Email Check
-- ==============================================================================

-- Create a table for public profiles
create table if not exists profiles (
  id uuid references auth.users not null primary key,
  email text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

-- Policies for Profiles
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'profiles' and policyname = 'Public profiles are viewable by everyone') then
    create policy "Public profiles are viewable by everyone"
      on profiles for select
      using ( true );
  end if;

  if not exists (select 1 from pg_policies where tablename = 'profiles' and policyname = 'Users can insert their own profile') then
    create policy "Users can insert their own profile"
      on profiles for insert
      with check ( auth.uid() = id );
  end if;

  if not exists (select 1 from pg_policies where tablename = 'profiles' and policyname = 'Users can update own profile') then
    create policy "Users can update own profile"
      on profiles for update
      using ( auth.uid() = id );
  end if;
end $$;

-- Function to handle new user signup
-- Using CREATE OR REPLACE allows updating the logic without deleting the function
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on every new user creation
do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'on_auth_user_created') then
    create trigger on_auth_user_created
      after insert on auth.users
      for each row execute procedure public.handle_new_user();
  end if;
end $$;
